export const Users = [
    {
      id:1,
      profilePicture: "https://images.pexels.com/photos/2584269/pexels-photo-2584269.jpeg?auto=compress&cs=tinysrgb&w=300",
      username: "Safak Kocaoglu",
    },
    {
      id:2,
      profilePicture: "https://images.pexels.com/photos/3651597/pexels-photo-3651597.jpeg?auto=compress&cs=tinysrgb&w=300",
      username: "Janell Shrum",
    },
    {
      id:3,
      profilePicture: "https://images.pexels.com/photos/10679231/pexels-photo-10679231.jpeg?auto=compress&cs=tinysrgb&w=300",
      username: "Alex Durden",
    },
    {
      id:4,
      profilePicture: "https://images.pexels.com/photos/1485031/pexels-photo-1485031.jpeg?auto=compress&cs=tinysrgb&w=300",
      username: "Dora Hawks",
    },
    {
      id:5,
      profilePicture: "https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&w=300",
      username: "Thomas Holden",
    },
    {
      id:6,
      profilePicture: "https://images.pexels.com/photos/4890733/pexels-photo-4890733.jpeg?auto=compress&cs=tinysrgb&w=300",
      username: "Shirley Beauchamp",
    },
    {
      id:7,
      profilePicture: "https://images.pexels.com/photos/1918445/pexels-photo-1918445.jpeg?auto=compress&cs=tinysrgb&w=300",
      username: "Travis Bennett",
    },
    {
      id:8,
      profilePicture: "https://images.pexels.com/photos/1857375/pexels-photo-1857375.jpeg?auto=compress&cs=tinysrgb&w=300",
      username: "Kristen Thomas",
    },
    {
      id:9,
      profilePicture: "https://images.pexels.com/photos/13315065/pexels-photo-13315065.jpeg?auto=compress&cs=tinysrgb&w=300",
      username: "Gary Duty",
    },
    {
      id:10,
      profilePicture: "https://images.pexels.com/photos/3078404/pexels-photo-3078404.jpeg?auto=compress&cs=tinysrgb&w=300",
      username: "Safak Kocaoglu",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "https://images.pexels.com/photos/3756030/pexels-photo-3756030.jpeg?auto=compress&cs=tinysrgb&w=300",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "https://images.pexels.com/photos/914668/pexels-photo-914668.jpeg?auto=compress&cs=tinysrgb&w=300",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg?auto=compress&cs=tinysrgb&w=300",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "https://images.pexels.com/photos/6441903/pexels-photo-6441903.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "https://images.pexels.com/photos/8915478/pexels-photo-8915478.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "https://images.pexels.com/photos/8276217/pexels-photo-8276217.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "https://images.pexels.com/photos/7763065/pexels-photo-7763065.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "https://images.pexels.com/photos/2764995/pexels-photo-2764995.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "https://images.pexels.com/photos/5026440/pexels-photo-5026440.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "https://images.pexels.com/photos/6193655/pexels-photo-6193655.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];